#!/usr/bin/env python3
"""Embed a BMP file as a C const byte array header.

Usage:
    python3 bmp_to_header.py time.bmp time_bmp.h

Produces a `const uint8_t time_bmp[]` (the variable name is derived from the
output stem) plus a `time_bmp_len` length constant. On the ESP32-S3 a `const`
array lives in memory-mapped flash, so no PROGMEM / pgm_read_* is needed — the
firmware indexes it like ordinary RAM.

Regenerate whenever poc/to-bmp emits a new frame: drop the new .bmp in as
time.bmp and re-run. Nothing here is BMP-aware; it is a raw byte dumper, so the
firmware remains the single source of truth for header parsing.
"""

import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 1

    src = Path(sys.argv[1])
    dst = Path(sys.argv[2])
    name = dst.stem  # e.g. "time_bmp"

    data = src.read_bytes()

    lines = [
        f"// Generated by bmp_to_header.py from {src.name} ({len(data)} bytes).",
        "// Do not edit by hand — regenerate when poc/to-bmp emits a new frame.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"const uint32_t {name}_len = {len(data)};",
        f"const uint8_t {name}[] = {{",
    ]

    per_row = 16
    for i in range(0, len(data), per_row):
        chunk = data[i : i + per_row]
        lines.append("    " + "".join(f"0x{b:02x}, " for b in chunk).rstrip())

    lines.append("};")
    lines.append("")

    dst.write_text("\n".join(lines))
    print(f"wrote {dst} ({len(data)} bytes -> {dst.stat().st_size} bytes of C source)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
